[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20", "python310", "python310Packages.pip"]

[phases.install]
cmds = ["pip install --pre -r requirements.txt --break-system-packages"]

[phases.start]
cmd = "python bot.py"
